# Generated by Django 2.2.1 on 2019-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=80)),
                ('Locate', models.CharField(max_length=15)),
            ],
        ),
    ]
